services:
  chaos-agent:
    build: .
    container_name: kubenova-chaos
    ports:
      - "9666:9666"
    volumes:
      - "./kubeconfig.yaml:/home/chaos/.kube/config:ro"
    restart: unless-stopped
    environment:
      - KUBECONFIG=/home/chaos/.kube/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
