// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type FlowTrackerFlowKey struct {
	_       structs.HostLayout
	SrcIp   uint32
	DstIp   uint32
	SrcPort uint16
	DstPort uint16
	Proto   uint8
	Pad     [3]uint8
}

type FlowTrackerFlowVal struct {
	_          structs.HostLayout
	Bytes      uint64
	Packets    uint64
	LastSeenNs uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	FlowTrackerMapFlows     = "flows"
	FlowTrackerProgTcEgress = "tc_egress"
)

// LoadFlowTracker returns the embedded CollectionSpec for FlowTracker.
func LoadFlowTracker() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FlowTrackerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load FlowTracker: %w", err)
	}

	return spec, err
}

// LoadFlowTrackerObjects loads FlowTracker and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*FlowTrackerObjects
//	*FlowTrackerPrograms
//	*FlowTrackerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadFlowTrackerObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadFlowTracker()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// FlowTrackerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FlowTrackerSpecs struct {
	FlowTrackerProgramSpecs
	FlowTrackerMapSpecs
	FlowTrackerVariableSpecs
}

// FlowTrackerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FlowTrackerProgramSpecs struct {
	TcEgress *ebpf.ProgramSpec `ebpf:"tc_egress"`
}

// FlowTrackerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FlowTrackerMapSpecs struct {
	Flows *ebpf.MapSpec `ebpf:"flows"`
}

// FlowTrackerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FlowTrackerVariableSpecs struct {
}

// FlowTrackerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadFlowTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type FlowTrackerObjects struct {
	FlowTrackerPrograms
	FlowTrackerMaps
	FlowTrackerVariables
}

func (o *FlowTrackerObjects) Close() error {
	return _FlowTrackerClose(
		&o.FlowTrackerPrograms,
		&o.FlowTrackerMaps,
	)
}

// FlowTrackerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadFlowTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type FlowTrackerMaps struct {
	Flows *ebpf.Map `ebpf:"flows"`
}

func (m *FlowTrackerMaps) Close() error {
	return _FlowTrackerClose(
		m.Flows,
	)
}

// FlowTrackerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadFlowTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type FlowTrackerVariables struct {
}

// FlowTrackerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadFlowTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type FlowTrackerPrograms struct {
	TcEgress *ebpf.Program `ebpf:"tc_egress"`
}

func (p *FlowTrackerPrograms) Close() error {
	return _FlowTrackerClose(
		p.TcEgress,
	)
}

func _FlowTrackerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed flowtracker_bpfeb.o
var _FlowTrackerBytes []byte
